language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

branches:
  except:
    - gh-pages

cache:
    directories:
        - "~/.platformio"

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
    - pip install -U platformio
    - platformio update

script:
    - |
      if [[ "$FLASH" == "1" ]]; then
        platformio run -e esp32dev || exit 1
      fi
    - |
      if [[ "$SNIFF" == "1" ]]; then
        platformio check -e esp32dev || exit 1
      fi

jobs:
  include:
    - name: Flash Arduino
      env: FLASH=1
    - name: Lint
      env: SNIFF=1
    - name: Deploy
      if: branch = master
      env:
        - DEPLOY: 1
        - GH_REPO_NAME: bottle-buddy-embedded
        - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
        - GH_REPO_REF: github.com/BottleBuddy/bottle-buddy-embedded.git
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - chmod +x generateDocumentation.sh
        - ./generateDocumentation.sh
